# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Blog
tagline:             Jon Schlinkert's Blog
description:         'Blog. Made by <a href="https://twitter.com/jonschlinkert" target="_blank">@jonschlinkert</a>.'
url:                 https://jonschlinkert.github.io/blog/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Jon Schlinkert
  url:               https://twitter.com/jonschlinkert
  email:             jon.schlinkert@sellside.com

# Custom vars
version:             0.1.0
